/* Classifarr - Copyright (C) 2024-2026 Classifarr Contributors - GPL-3.0 */
const valid = { version: 1, tmdb_id: 7, media_type: 'movie', keywords: ['space'], original_language: 'en' };

/** Explicit contract expectations, independent of the production validator's output. */
export const inventoryObservationValidityCases = [
    ['complete', true, {}],
    ['empty capture', true, { keywords: [], original_language: null }],
    ['duplicate keywords', true, { keywords: ['space', 'space'] }],
    ['unknown language', true, { original_language: null }],
    ['canonical subtags', true, { original_language: 'zh-hans' }],
    ['normalized Unicode', true, { keywords: ['café'] }],
    ['keyword string', false, { keywords: 'invalid' }],
    ['keyword object', false, { keywords: {} }],
    ['keyword null', false, { keywords: null }],
    ['keyword missing', false, { keywords: undefined }],
    ['too many keywords', false, { keywords: Array(501).fill('space') }],
    ['numeric keyword', false, { keywords: [7] }],
    ['nested keyword', false, { keywords: [['space']] }],
    ['padded keyword', false, { keywords: [' space '] }],
    ['control keyword', false, { keywords: ['space\ntravel'] }],
    ['compatibility keyword', false, { keywords: ['ｓｐａｃｅ'] }],
    ['empty keyword', false, { keywords: [''] }],
    ['placeholder keyword', false, { keywords: ['UNKNOWN'] }],
    ['long keyword', false, { keywords: ['x'.repeat(161)] }],
    ['string version', false, { version: '1' }],
    ['wrong version', false, { version: 2 }],
    ['wrong identity', false, { tmdb_id: 8 }],
    ['string identity', false, { tmdb_id: '7' }],
    ['wrong type', false, { media_type: 'tv' }],
    ['missing language', false, { original_language: undefined }],
    ['uppercase language', false, { original_language: 'EN' }],
    ['language alias', false, { original_language: 'iw' }],
    ['malformed language', false, { original_language: 'en_XX' }],
    ['placeholder language', false, { original_language: 'und' }],
    ['language object', false, { original_language: {} }],
    ['null record', false, null],
    ['missing record', false, undefined],
].map(([name, reusable, override]) => ({ name, reusable,
    record: override == null ? override : { ...valid, ...override } }));
