/* Classifarr - Copyright (C) 2024-2026 Classifarr Contributors - GPL-3.0 */
import { installScopedRepairPrototype } from '../libraryScopedRepair/schema.mjs';

/** Caller owns installation transaction; the existing installer refuses application databases. */
export async function installSyncCompatibilityPrototype(db) {
    await installScopedRepairPrototype(db, 'disposable');
    await db.query(`CREATE TABLE scoped_repair_lab.sync_servers(id integer PRIMARY KEY);
        CREATE TABLE scoped_repair_lab.sync_libraries(id integer PRIMARY KEY);
        ALTER TABLE scoped_repair_lab.scoped_repair_source
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY,
            ADD COLUMN media_server_id integer REFERENCES scoped_repair_lab.sync_servers ON DELETE CASCADE,
            ADD COLUMN external_id varchar(100) NOT NULL, ADD COLUMN imdb_id varchar(20), ADD COLUMN tvdb_id integer,
            ADD COLUMN title varchar(500) NOT NULL, ADD COLUMN original_title varchar(500), ADD COLUMN year integer,
            ADD COLUMN genres text[], ADD COLUMN tags text[], ADD COLUMN collections text[], ADD COLUMN studio varchar(255),
            ADD COLUMN content_rating varchar(20), ADD COLUMN original_rating varchar(10),
            ADD COLUMN added_at timestamp, ADD COLUMN last_synced timestamp,
            ADD UNIQUE(media_server_id,external_id),
            ADD FOREIGN KEY(library_id) REFERENCES scoped_repair_lab.sync_libraries ON DELETE CASCADE;`);
}
