/*
 * Classifarr - AI-powered media classification for the *arr ecosystem
 * Copyright (C) 2024-2026 Classifarr Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

import { asyncHandler } from '../utils/asyncHandler.mjs';
import { buildAutoGeneratedRules } from './librariesRouteRuleHelpers.mjs';

export function registerRuleSuggestionRoutes(router, { db, ollamaService, normalizeMetadataListLower, requireReadWrite, metadataEnrichment, logger }) {
  router.get('/:id/rules/suggest', asyncHandler(async (req, res) => {
      const { id } = req.params;

      const analysis = await db.query(
        `
      SELECT 
        array_agg(DISTINCT content_rating) FILTER (WHERE content_rating IS NOT NULL) as ratings,
        array_agg(DISTINCT g) FILTER (WHERE g IS NOT NULL) as genres,
        array_agg(DISTINCT msi.metadata->>'original_language') FILTER (WHERE msi.metadata->>'original_language' IS NOT NULL) as languages,
        COUNT(*) as total_items
      FROM media_server_items msi
        LEFT JOIN LATERAL UNNEST(msi.genres) as g ON true
      WHERE msi.library_id = $1
    `,
        [id]
      );

      const existingRulesResult = await db.query('SELECT rule_type, value FROM library_rules WHERE library_id = $1', [id]);
      const existingRules = existingRulesResult.rows;

      const data = analysis.rows[0];
      const suggestions = [];

      const ruleExists = (type, val) => {
        return existingRules.some((r) => r.rule_type === type && (r.value === val || r.value.includes(val)));
      };

      if (data.ratings && data.ratings.length > 0 && data.ratings.length <= 5) {
        const val = data.ratings.join(',');
        if (!ruleExists('rating', val)) {
          suggestions.push({
            rule_type: 'rating',
            operator: 'includes',
            value: val,
            description: `Only ratings: ${data.ratings.join(', ')}`,
            is_exception: false,
          });
        }
      }

      if (data.genres && data.genres.length > 0) {
        const topGenres = data.genres.slice(0, 5);
        const val = topGenres.join(',');
        if (!ruleExists('genre', val)) {
          suggestions.push({
            rule_type: 'genre',
            operator: 'includes',
            value: val,
            description: `Common genres: ${topGenres.join(', ')}`,
            is_exception: false,
          });
        }
      }

      if (data.languages && data.languages.length === 1 && data.languages[0] !== 'en') {
        const val = data.languages[0];
        if (!ruleExists('language', val)) {
          suggestions.push({
            rule_type: 'language',
            operator: 'equals',
            value: val,
            description: `Only ${val} content${val === 'ja' ? ' (Anime)' : ''}`,
            is_exception: false,
          });
        }
      }

      const keywordAnalysis = await db.query(
        `
      SELECT 
        COUNT(*) FILTER (WHERE LOWER(title) LIKE '%christmas%' OR LOWER(title) LIKE '%xmas%') as christmas_count,
        COUNT(*) FILTER (WHERE LOWER(title) LIKE '%holiday%') as holiday_count,
        COUNT(*) FILTER (WHERE LOWER(title) LIKE '%hallmark%' OR LOWER(msi.studio) LIKE '%hallmark%') as hallmark_count,
        COUNT(*) as total
      FROM media_server_items msi
      WHERE msi.library_id = $1
    `,
        [id]
      );

      const kw = keywordAnalysis.rows[0];
      const total = parseInt(kw.total) || 1;
      const christmasRatio = parseInt(kw.christmas_count) / total;
      const holidayRatio = parseInt(kw.holiday_count) / total;
      const hallmarkRatio = parseInt(kw.hallmark_count) / total;

      if (christmasRatio >= 0.3) {
        const val = 'christmas,xmas,holiday,santa,snowman,elf';
        if (!ruleExists('keyword', val)) {
          suggestions.push({
            rule_type: 'keyword',
            operator: 'contains',
            value: val,
            description: `Christmas/Holiday content (${Math.round(christmasRatio * 100)}% match)`,
            is_exception: false,
          });
        }
      } else if (holidayRatio >= 0.3) {
        const val = 'holiday,christmas,seasonal';
        if (!ruleExists('keyword', val)) {
          suggestions.push({
            rule_type: 'keyword',
            operator: 'contains',
            value: val,
            description: `Holiday content (${Math.round(holidayRatio * 100)}% match)`,
            is_exception: false,
          });
        }
      }

      if (hallmarkRatio >= 0.3) {
        const val = 'hallmark';
        if (!ruleExists('keyword', val)) {
          suggestions.push({
            rule_type: 'keyword',
            operator: 'contains',
            value: val,
            description: `Hallmark productions (${Math.round(hallmarkRatio * 100)}% match)`,
            is_exception: false,
          });
        }
      }

      const libraryResult = await db.query('SELECT name FROM libraries WHERE id = $1', [id]);
      const libraryName = libraryResult.rows[0]?.name?.toLowerCase() || '';

      const normalizedGenres = normalizeMetadataListLower(data.genres);
      const hasAnimeGenre =
        normalizedGenres.includes('animation') ||
        normalizedGenres.includes('anime') ||
        normalizedGenres.some((g) => g.includes('anime'));

      const isJapanese = data.languages && data.languages.includes('ja');
      const libraryIsAnime = libraryName.includes('anime');

      if ((hasAnimeGenre && isJapanese) || (hasAnimeGenre && libraryIsAnime)) {
        if (!ruleExists('language', 'ja')) {
          suggestions.push({
            rule_type: 'language',
            operator: 'equals',
            value: 'ja',
            description: 'Japanese Anime content',
            is_exception: false,
          });
        }

        const animeVal = 'Animation,Anime';
        if (
          !ruleExists('genre', animeVal) &&
          !suggestions.find((s) => s.rule_type === 'genre' && s.value.includes('Animation'))
        ) {
          suggestions.push({
            rule_type: 'genre',
            operator: 'includes',
            value: animeVal,
            description: 'Anime/Animation content',
            is_exception: false,
          });
        }
      }

      res.json({
        totalItems: parseInt(data.total_items) || 0,
        suggestions,
      });
  }));

  router.get('/:id/rules/smart-suggest', asyncHandler(async (req, res) => {
      const { id } = req.params;

      const libraryResult = await db.query('SELECT * FROM libraries WHERE id = $1', [id]);
      if (libraryResult.rows.length === 0) {
        return res.status(404).json({ error: 'Library not found' });
      }
      const library = libraryResult.rows[0];

      const contentTypeResult = await db.query(
        `
      SELECT 
        metadata->'content_analysis'->>'type' as content_type,
        COUNT(*) as count
      FROM media_server_items 
      WHERE library_id = $1 
        AND metadata->'content_analysis' IS NOT NULL
        AND metadata->'content_analysis'->>'type' != 'source_library'
      GROUP BY content_type
      ORDER BY count DESC
      LIMIT 10
    `,
        [id]
      );

      const genreResult = await db.query(
        `
      SELECT unnest(genres) as genre, COUNT(*) as count
      FROM media_server_items
      WHERE library_id = $1 AND genres IS NOT NULL
      GROUP BY genre
      ORDER BY count DESC
      LIMIT 10
    `,
        [id]
      );

      const ratingResult = await db.query(
        `
      SELECT content_rating, COUNT(*) as count
      FROM media_server_items
      WHERE library_id = $1 AND content_rating IS NOT NULL
      GROUP BY content_rating
      ORDER BY count DESC
    `,
        [id]
      );

      const languageResult = await db.query(
        `
      SELECT metadata->>'original_language' as language, COUNT(*) as count
      FROM media_server_items
      WHERE library_id = $1 AND metadata->>'original_language' IS NOT NULL
      GROUP BY language
      ORDER BY count DESC
      LIMIT 5
    `,
        [id]
      );

      const keywordResult = await db.query(
        `
      SELECT unnest(tags) as keyword, COUNT(*) as count
      FROM media_server_items
      WHERE library_id = $1 AND tags IS NOT NULL AND array_length(tags, 1) > 0
      GROUP BY keyword
      ORDER BY count DESC
      LIMIT 20
    `,
        [id]
      );

      const { TAVILY_METADATA_KEYS, buildJsonbPresenceOr } = metadataEnrichment;
      const tavilyEnrichmentSql = buildJsonbPresenceOr('metadata', TAVILY_METADATA_KEYS);

      const countResult = await db.query(
        `
      SELECT 
        COUNT(*) as total,
        COUNT(*) FILTER (WHERE metadata->'content_analysis' IS NOT NULL) as analyzed,
        COUNT(*) FILTER (WHERE ${tavilyEnrichmentSql}) as tavily_enriched,
        MAX(added_at) as last_item_added
      FROM media_server_items
      WHERE library_id = $1
    `,
        [id]
      );

      const suggestionMetaResult = await db.query(
        `
      SELECT last_analyzed, pending_count
      FROM library_pattern_suggestions
      WHERE library_id = $1
    `,
        [id]
      );
      const suggestionMeta = suggestionMetaResult.rows[0] || null;

      const tavilyInsightsResult = await db.query(
        `
      SELECT 
        metadata->'tavily_advisory'->>'answer' as advisory_insight,
        metadata->'tavily_imdb'->>'answer' as imdb_insight,
        metadata->'tavily_holiday'->>'answer' as holiday_insight,
        metadata->'tavily_anime'->>'answer' as anime_insight
      FROM media_server_items
      WHERE library_id = $1 
        AND (${tavilyEnrichmentSql})
      LIMIT 5
    `,
        [id]
      );

      const tavilyInsights = tavilyInsightsResult.rows
        .flatMap((r) => [r.advisory_insight, r.imdb_insight, r.holiday_insight, r.anime_insight])
        .filter(Boolean)
        .slice(0, 3);

      const existingRulesResult = await db.query(
        `SELECT name, conditions FROM library_rules_v2 WHERE library_id = $1`,
        [id]
      );
      const existingRules = existingRulesResult.rows;

      const stats = {
        libraryName: library.name,
        mediaType: library.media_type,
        totalItems: parseInt(countResult.rows[0]?.total) || 0,
        analyzedItems: parseInt(countResult.rows[0]?.analyzed) || 0,
        tavilyEnrichedItems: parseInt(countResult.rows[0]?.tavily_enriched) || 0,
        contentTypes: contentTypeResult.rows.map((r) => ({ type: r.content_type, count: parseInt(r.count) })),
        genres: genreResult.rows.map((r) => ({ genre: r.genre, count: parseInt(r.count) })),
        ratings: ratingResult.rows.map((r) => ({ rating: r.content_rating, count: parseInt(r.count) })),
        languages: languageResult.rows.map((r) => ({ language: r.language, count: parseInt(r.count) })),
        keywords: keywordResult.rows.map((r) => ({ keyword: r.keyword, count: parseInt(r.count) })),
        tavilyInsights,
      };

      const existingRulesSection = existingRules.length > 0
        ? `\nEXISTING RULES (DO NOT SUGGEST DUPLICATES OF THESE):
${existingRules.map((r) => `- "${r.name}": ${JSON.stringify(r.conditions)}`).join('\n')}
`
        : '';

      const prompt = `You are an AI assistant helping to create classification rules for a media library.

Library Name: "${stats.libraryName}"
Media Type: ${stats.mediaType}
Total Items: ${stats.totalItems}, Analyzed: ${stats.analyzedItems}, Web-Enriched: ${stats.tavilyEnrichedItems}
${existingRulesSection}

Content Types (from AI analysis):
${stats.contentTypes.map((t) => `- ${t.type}: ${t.count} items`).join('\n') || 'No AI analysis available yet'}

Genres:
${stats.genres.map((g) => `- ${g.genre}: ${g.count} items`).join('\n') || 'No genre data'}

Content Ratings:
${stats.ratings.map((r) => `- ${r.rating}: ${r.count} items`).join('\n') || 'No rating data'}

Languages:
${stats.languages.map((l) => `- ${l.language}: ${l.count} items`).join('\n') || 'No language data'}

Keywords/Tags:
${stats.keywords.slice(0, 10).map((k) => `- ${k.keyword}: ${k.count} items`).join('\n') || 'No keyword data'}

${stats.tavilyInsights.length > 0 ? `Web Search Insights (from IMDB/content advisories):
${stats.tavilyInsights.map((insight) => `- ${insight}`).join('\n')}

` : ''}Based on the library name and this data, suggest 2-4 classification rules that would best define what content belongs in this library. For each rule, provide:
1. A descriptive name
2. The conditions (field, operator, value)
3. A confidence score (0-100) based on how well the data supports this rule
4. Brief reasoning

IMPORTANT: Do NOT suggest rules that duplicate or closely match any existing rules listed above. You may suggest enhancements or variations that add value, but not identical or near-identical rules.

Respond in this exact JSON format:
{"suggestions": [{"name": "Rule Name", "conditions": [{"field": "genre", "operator": "contains", "value": "Horror"}], "confidence": 85, "reasoning": "Brief explanation"}]}

Valid fields: genre, content_type, rating, language, keyword
Valid operators: equals, contains, includes`;

      let llmSuggestions = [];
      try {
        const configResult = await db.query('SELECT * FROM ollama_config WHERE is_active = true LIMIT 1');
        if (configResult.rows.length > 0) {
          const config = configResult.rows[0];
          const response = await ollamaService.generate(prompt, config.model, parseFloat(config.temperature) || 0.3);

          const jsonMatch = response.match(/\{[\s\S]*\}/);
          if (jsonMatch) {
            const parsed = JSON.parse(jsonMatch[0]);
            llmSuggestions = parsed.suggestions || [];

            if (existingRules.length > 0) {
              llmSuggestions = llmSuggestions.filter((suggestion) => {
                return !existingRules.some((existingRule) => {
                  const existingConditions = existingRule.conditions || [];
                  const suggestedConditions = suggestion.conditions || [];

                  return suggestedConditions.some((sc) =>
                    existingConditions.some(
                      (ec) => ec.field === sc.field && String(ec.value).toLowerCase() === String(sc.value).toLowerCase()
                    )
                  );
                });
              });
            }

            llmSuggestions = llmSuggestions
              .map((suggestion) => ({
                ...suggestion,
                conditions: (suggestion.conditions || []).filter((c) => c.field !== 'content_type'),
              }))
              .filter((suggestion) => suggestion.conditions && suggestion.conditions.length > 0);
          }
        }
      } catch (llmError) {
        logger.warn('LLM suggestion generation failed', { error: llmError.message });
      }

      const dataSuggestions = [];

      if (stats.genres.length > 0) {
        const top = stats.genres[0];
        const confidence = Math.round((top.count / stats.totalItems) * 100);
        dataSuggestions.push({
          name: `${top.genre} Genre`,
          conditions: [{ field: 'genre', operator: 'contains', value: top.genre }],
          confidence,
          reasoning: `${confidence}% of items have ${top.genre} genre`,
        });
      }

      if (stats.ratings.length > 0 && stats.ratings.length <= 3) {
        const topRatings = stats.ratings.slice(0, 2).map((r) => r.rating);
        const totalCount = stats.ratings.slice(0, 2).reduce((sum, r) => sum + r.count, 0);
        const confidence = Math.round((totalCount / stats.totalItems) * 100);
        dataSuggestions.push({
          name: `${topRatings.join('/')} Rated Content`,
          conditions: [{ field: 'rating', operator: 'includes', value: topRatings.join(',') }],
          confidence,
          reasoning: `${confidence}% of items are ${topRatings.join(' or ')} rated`,
        });
      }

      if (stats.languages.length > 0) {
        const top = stats.languages[0];
        const confidence = Math.round((top.count / stats.totalItems) * 100);
        if (confidence >= 50 && top.language !== 'en') {
          const languageNames = {
            ja: 'Japanese',
            ko: 'Korean',
            zh: 'Chinese',
            es: 'Spanish',
            fr: 'French',
            de: 'German',
            it: 'Italian',
            pt: 'Portuguese',
            ru: 'Russian',
            hi: 'Hindi',
          };
          const langName = languageNames[top.language] || top.language.toUpperCase();
          dataSuggestions.push({
            name: `${langName} Language Content`,
            conditions: [{ field: 'language', operator: 'equals', value: top.language }],
            confidence,
            reasoning: `${confidence}% of items are in ${langName}`,
          });
        }
      }

      if (stats.keywords.length > 0) {
        const topKeywords = stats.keywords.slice(0, 3);
        for (const kw of topKeywords) {
          const confidence = Math.round((kw.count / stats.totalItems) * 100);
          if (confidence >= 20) {
            dataSuggestions.push({
              name: `${kw.keyword.charAt(0).toUpperCase() + kw.keyword.slice(1)} Keyword`,
              conditions: [{ field: 'keyword', operator: 'contains', value: kw.keyword }],
              confidence,
              reasoning: `${confidence}% of items have keyword "${kw.keyword}"`,
            });
          }
        }
      }

      const kidsRatings = ['G', 'PG', 'TV-Y', 'TV-Y7', 'TV-G', 'TV-PG'];
      const kidsRatingCounts = stats.ratings.filter((r) => kidsRatings.includes(r.rating));
      if (kidsRatingCounts.length > 0) {
        const kidsTotal = kidsRatingCounts.reduce((sum, r) => sum + r.count, 0);
        const kidsConfidence = Math.round((kidsTotal / stats.totalItems) * 100);
        if (kidsConfidence >= 70) {
          dataSuggestions.push({
            name: 'Kids-Friendly Content',
            conditions: [{ field: 'rating', operator: 'includes', value: kidsRatings.join(',') }],
            confidence: kidsConfidence,
            reasoning: `${kidsConfidence}% of items have kids-friendly ratings (${kidsRatingCounts
              .map((r) => r.rating)
              .join(', ')})`,
          });
        }
      }

      const libraryLower = stats.libraryName.toLowerCase();
      const hasAnimeInName = libraryLower.includes('anime');
      const hasJapanese = stats.languages.some((l) => l.language === 'ja');
      const normalizedGenres = stats.genres.map((g) => String(g.genre || '').toLowerCase());
      const hasAnimation = normalizedGenres.includes('animation') || normalizedGenres.some((g) => g.includes('anime'));

      if (hasAnimeInName || (hasJapanese && hasAnimation)) {
        const japaneseCount = stats.languages.find((l) => l.language === 'ja')?.count || 0;
        const animationCount = stats.genres.find((g) => String(g.genre || '').toLowerCase() === 'animation')?.count || 0;
        const combinedConfidence = Math.round(
          Math.max(
            (japaneseCount / stats.totalItems) * 100,
            (animationCount / stats.totalItems) * 100,
            hasAnimeInName ? 90 : 0
          )
        );

        if (combinedConfidence >= 50) {
          dataSuggestions.push({
            name: 'Anime Content',
            conditions: [
              { field: 'language', operator: 'equals', value: 'ja' },
              { field: 'genre', operator: 'contains', value: 'Animation' },
            ],
            confidence: combinedConfidence,
            reasoning: `Library appears to be for Anime content (${hasAnimeInName ? 'name indicates anime' : 'Japanese animation detected'})`,
          });
        }
      }

      const lastItemTime = countResult.rows[0]?.last_item_added;
      const lastAnalyzed = suggestionMeta?.last_analyzed;
      const hasNewData = !lastAnalyzed || (lastItemTime && new Date(lastItemTime) > new Date(lastAnalyzed));

      res.json({
        stats,
        suggestions: llmSuggestions.length > 0 ? llmSuggestions : dataSuggestions,
        source: llmSuggestions.length > 0 ? 'llm' : 'data-analysis',
        lastAnalyzed: lastAnalyzed ? new Date(lastAnalyzed).toISOString() : null,
        lastItemAdded: lastItemTime ? new Date(lastItemTime).toISOString() : null,
        hasNewData,
        analyzedAt: new Date().toISOString(),
      });
  }));

  router.post('/:id/rules/auto-generate', requireReadWrite, asyncHandler(async (req, res) => {
      const { id } = req.params;

      const libraryResult = await db.query('SELECT * FROM libraries WHERE id = $1', [id]);
      if (libraryResult.rows.length === 0) {
        return res.status(404).json({ error: 'Library not found' });
      }

      const library = libraryResult.rows[0];

      const existingRules = await db.query('SELECT rule_type, value FROM library_rules WHERE library_id = $1', [id]);
      const existingRuleKeys = new Set(existingRules.rows.map((r) => `${r.rule_type}:${r.value}`));
      const rules = buildAutoGeneratedRules(library.name, { existingRuleKeys });

      let created = 0;
      for (const rule of rules) {
        await db.query(
          `INSERT INTO library_rules (library_id, rule_type, operator, value, is_exception, priority, description)
         VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [id, rule.rule_type, rule.operator, rule.value, rule.is_exception, rule.priority, rule.description]
        );
        created++;
      }

      logger.info('Auto-generated library rules', { libraryId: id, libraryName: library.name, rulesCreated: created });

      res.json({
        success: true,
        libraryName: library.name,
        rulesCreated: created,
        rules,
      });
  }));

  router.post('/auto-generate-all', requireReadWrite, asyncHandler(async (req, res) => {
      const libraries = await db.query('SELECT id FROM libraries WHERE is_active = true');
      let totalCreated = 0;

      for (const lib of libraries.rows) {
        const checkExisting = await db.query('SELECT COUNT(*) FROM library_rules WHERE library_id = $1', [lib.id]);

        if (parseInt(checkExisting.rows[0].count) === 0) {
          const libraryResult = await db.query('SELECT * FROM libraries WHERE id = $1', [lib.id]);
          if (libraryResult.rows.length > 0) {
            const library = libraryResult.rows[0];
            const rules = buildAutoGeneratedRules(library.name, { includeExtendedPatterns: false });

            for (const rule of rules) {
              await db.query(
                `INSERT INTO library_rules (library_id, rule_type, operator, value, is_exception, priority, description)
               VALUES ($1, $2, $3, $4, $5, $6, $7)`,
                [lib.id, rule.rule_type, rule.operator, rule.value, rule.is_exception, rule.priority, rule.description]
              );
              totalCreated++;
            }
          }
        }
      }

      res.json({ success: true, totalRulesCreated: totalCreated });
  }));
}
