/*
 * Classifarr - AI-powered media classification for the *arr ecosystem
 * Copyright (C) 2024-2026 Classifarr Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

export function buildAutoGeneratedRules(
  libraryName,
  {
    existingRuleKeys = new Set(),
    includeExtendedPatterns = true,
  } = {}
) {
  const normalizedLibraryName = String(libraryName || '').toLowerCase();
  const rules = [];

  const addRule = (rule) => {
    const key = `${rule.rule_type}:${rule.value}`;
    if (!existingRuleKeys.has(key)) {
      rules.push(rule);
      existingRuleKeys.add(key);
    }
  };

  if (
    normalizedLibraryName.includes('kid') ||
    normalizedLibraryName.includes('family') ||
    normalizedLibraryName.includes('child')
  ) {
    addRule({
      rule_type: 'rating',
      operator: 'includes',
      value: 'G,PG,TV-Y,TV-Y7,TV-G,TV-PG',
      description: 'Kids-friendly ratings only',
      is_exception: false,
      priority: 0,
    });
  }

  if (
    normalizedLibraryName.includes('christmas') ||
    normalizedLibraryName.includes('holiday') ||
    normalizedLibraryName.includes('xmas') ||
    normalizedLibraryName.includes('hallmark')
  ) {
    addRule({
      rule_type: 'keyword',
      operator: 'contains',
      value: 'christmas,holiday,santa,xmas,hallmark',
      description: 'Holiday/Christmas themed content',
      is_exception: true,
      priority: 0,
    });
  }

  if (normalizedLibraryName.includes('anime')) {
    addRule({
      rule_type: 'genre',
      operator: 'includes',
      value: 'animation,anime',
      description: 'Anime/Animation genre',
      is_exception: false,
      priority: 0,
    });
    addRule({
      rule_type: 'language',
      operator: 'equals',
      value: 'ja',
      description: 'Japanese language content',
      is_exception: false,
      priority: 1,
    });
  }

  if (
    normalizedLibraryName.includes('comedy') ||
    normalizedLibraryName.includes('standup') ||
    (includeExtendedPatterns && normalizedLibraryName.includes('stand-up'))
  ) {
    addRule({
      rule_type: 'genre',
      operator: 'includes',
      value: 'comedy',
      description: 'Comedy genre',
      is_exception: false,
      priority: 0,
    });
  }

  if (
    normalizedLibraryName.includes('horror') ||
    (includeExtendedPatterns && normalizedLibraryName.includes('scary'))
  ) {
    addRule({
      rule_type: 'genre',
      operator: 'includes',
      value: 'horror,thriller',
      description: 'Horror/Thriller genre',
      is_exception: false,
      priority: 0,
    });
  }

  if (
    normalizedLibraryName.includes('documentary') ||
    normalizedLibraryName.includes('doc')
  ) {
    addRule({
      rule_type: 'genre',
      operator: 'includes',
      value: 'documentary',
      description: 'Documentary genre',
      is_exception: false,
      priority: 0,
    });
  }

  if (includeExtendedPatterns && normalizedLibraryName.includes('action')) {
    addRule({
      rule_type: 'genre',
      operator: 'includes',
      value: 'action,adventure',
      description: 'Action/Adventure genre',
      is_exception: false,
      priority: 0,
    });
  }

  if (
    includeExtendedPatterns &&
    (normalizedLibraryName.includes('sci-fi') ||
      normalizedLibraryName.includes('scifi') ||
      normalizedLibraryName.includes('science fiction'))
  ) {
    addRule({
      rule_type: 'genre',
      operator: 'includes',
      value: 'science fiction,sci-fi',
      description: 'Science Fiction genre',
      is_exception: false,
      priority: 0,
    });
  }

  return rules;
}
