/*
 * Classifarr - AI-powered media classification for the *arr ecosystem
 * Copyright (C) 2024-2026 Classifarr Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

import { asyncHandler } from '../utils/asyncHandler.mjs';
import { buildAutoGeneratedRules } from './librariesRouteRuleHelpers.mjs';

export function registerAutoGenerateRoutes(router, { db, requireReadWrite, logger }) {
  router.post('/:id/rules/auto-generate', requireReadWrite, asyncHandler(async (req, res) => {
      const { id } = req.params;

      const libraryResult = await db.query('SELECT * FROM libraries WHERE id = $1', [id]);
      if (libraryResult.rows.length === 0) {
        return res.status(404).json({ error: 'Library not found' });
      }

      const library = libraryResult.rows[0];

      const existingRules = await db.query('SELECT rule_type, value FROM library_rules WHERE library_id = $1', [id]);
      const existingRuleKeys = new Set(existingRules.rows.map((r) => `${r.rule_type}:${r.value}`));
      const rules = buildAutoGeneratedRules(library.name, { existingRuleKeys });

      let created = 0;
      for (const rule of rules) {
        await db.query(
          `INSERT INTO library_rules (library_id, rule_type, operator, value, is_exception, priority, description)
         VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [id, rule.rule_type, rule.operator, rule.value, rule.is_exception, rule.priority, rule.description]
        );
        created++;
      }

      logger.info('Auto-generated library rules', { libraryId: id, libraryName: library.name, rulesCreated: created });

      res.json({
        success: true,
        libraryName: library.name,
        rulesCreated: created,
        rules,
      });
  }));

  router.post('/auto-generate-all', requireReadWrite, asyncHandler(async (req, res) => {
      const libraries = await db.query('SELECT id FROM libraries WHERE is_active = true');
      let totalCreated = 0;

      for (const lib of libraries.rows) {
        const checkExisting = await db.query('SELECT COUNT(*) FROM library_rules WHERE library_id = $1', [lib.id]);

        if (parseInt(checkExisting.rows[0].count) === 0) {
          const libraryResult = await db.query('SELECT * FROM libraries WHERE id = $1', [lib.id]);
          if (libraryResult.rows.length > 0) {
            const library = libraryResult.rows[0];
            const rules = buildAutoGeneratedRules(library.name, { includeExtendedPatterns: false });

            for (const rule of rules) {
              await db.query(
                `INSERT INTO library_rules (library_id, rule_type, operator, value, is_exception, priority, description)
               VALUES ($1, $2, $3, $4, $5, $6, $7)`,
                [lib.id, rule.rule_type, rule.operator, rule.value, rule.is_exception, rule.priority, rule.description]
              );
              totalCreated++;
            }
          }
        }
      }

      res.json({ success: true, totalRulesCreated: totalCreated });
  }));
}
