/* Classifarr - Copyright (C) 2024-2026 Classifarr Contributors - GPL-3.0 */
import { expect, test } from '@playwright/test'

test('tag commands preserve drafts and focus without submitting a form', async ({ page }, testInfo) => {
  const errors = [], apiRequests = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(url => url.pathname.startsWith('/api/'), async route => {
    apiRequests.push(route.request().method())
    await route.abort()
  })
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const input = page.getByRole('textbox', { name: 'Keywords', exact: true })
  const add = page.getByRole('button', { name: 'Add tag to Keywords', exact: true })
  await page.getByText('Keywords', { exact: true }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveAccessibleDescription('Enter adds a tag. Backspace removes the last tag when the entry is empty.')
  await input.fill('draft')
  await page.getByRole('button', { name: 'Remove first from Keywords', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('draft')
  await expect(page.getByLabel('Tag values')).toHaveText('["last"]')
  await input.press('Enter')
  await expect(page.getByLabel('Tag values')).toHaveText('["last","draft"]')
  const remove = page.getByRole('button', { name: 'Remove last from Keywords', exact: true })
  await remove.focus()
  await remove.press('Space')
  await expect(input).toBeFocused()
  await page.getByRole('button', { name: 'Remove draft from Keywords', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(input).toBeFocused()
  await expect(page.getByLabel('Tag values')).toHaveText('[]')
  await input.fill('touch')
  await add.click()
  await expect(input).toBeFocused()
  await input.fill('blur')
  await input.press('Tab')
  await expect(add).toBeFocused()
  await expect(page.getByLabel('Tag values')).toHaveText('["touch"]')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Save sample tags' })).toBeFocused()
  await expect(page.getByLabel('Tag values')).toHaveText('["touch","blur"]')
  await expect(page.getByLabel('Tag deliveries')).toHaveText('6')
  await expect(page.getByLabel('Tag submissions')).toHaveText('0')
  await page.getByLabel('Disable tags').check()
  await expect(input).toBeDisabled()
  await expect(add).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Remove touch from Keywords', exact: true })).toBeDisabled()
  await expect(page.getByLabel('Read-only tags', { exact: true })).not.toBeEditable()
  await expect(page.getByRole('button', { name: 'Remove protected from Read-only tags', exact: true })).toBeDisabled()
  await page.getByLabel('Disable tags').uncheck()
  await page.setViewportSize({ width: 390, height: 844 })
  await input.fill('very-long-domain-'.repeat(8) + 'example.test')
  await input.press('Enter')
  await input.press('Tab')
  expect(await add.evaluate(button => globalThis.getComputedStyle(button).outlineStyle)).not.toBe('none')
  expect(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('tag-input-mobile.png'), fullPage: true })
  expect(apiRequests).toEqual([])
  expect(errors).toEqual([])
})

test('tag editor waits for composition and does not repeat empty Backspace removals', async ({ page }) => {
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const input = page.getByRole('textbox', { name: 'Keywords', exact: true })
  await input.focus()
  // Synthetic composition protocol coverage; this is not an OS/IME certification.
  await input.dispatchEvent('compositionstart')
  await input.fill('日本語')
  await input.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(page.getByLabel('Tag deliveries')).toHaveText('0')
  await input.dispatchEvent('compositionend')
  await input.press('Enter')
  await expect(page.getByLabel('Tag values')).toHaveText('["first","last","日本語"]')
  await input.press('Backspace')
  await input.dispatchEvent('keydown', { key: 'Backspace', repeat: true })
  await expect(page.getByLabel('Tag values')).toHaveText('["first","last"]')
  await expect(page.getByLabel('Tag deliveries')).toHaveText('2')
  await input.dispatchEvent('compositionstart')
  await input.fill('中文')
  await input.evaluate(element => {
    element.blur()
    element.dispatchEvent(new globalThis.CompositionEvent('compositionend', { bubbles: true }))
    element.dispatchEvent(new globalThis.Event('input', { bubbles: true }))
  })
  await expect(page.getByLabel('Tag values')).toHaveText('["first","last","中文"]')
  await expect(input).toHaveValue('')
  await input.focus()
  await input.dispatchEvent('compositionstart')
  await input.fill('再見')
  await input.evaluate(element => element.blur())
  await page.getByRole('button', { name: 'Add tag to Keywords', exact: true }).focus()
  await input.dispatchEvent('compositionend')
  await expect(page.getByLabel('Tag deliveries')).toHaveText('3')
  await expect(input).toHaveValue('再見')
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Tag values')).toHaveText('["first","last","中文","再見"]')
  await expect(page.getByLabel('Tag deliveries')).toHaveText('4')
  await expect(page.getByLabel('Tag submissions')).toHaveText('0')
})

test('real controls have names, native keyboard behavior and stable model types', async ({ page }) => {
  const errors = [], apiRequests = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(url => url.pathname.startsWith('/api/'), async route => {
    apiRequests.push(route.request().method())
    await route.abort()
  })
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const priority = page.getByRole('spinbutton', { name: 'Priority', exact: true })
  const choice = page.getByRole('combobox', { name: 'Route', exact: true })
  const toggle = page.getByRole('switch', { name: 'Enabled', exact: true })
  const slider = page.getByRole('slider', { name: 'Threshold', exact: true })
  const button = page.getByRole('button', { name: 'Confirm choice', exact: true })
  await expect(page.getByLabel('Listener deliveries')).toHaveText('{"input":0,"select":0,"toggle":0,"slider":0,"button":0}')
  await expect(priority).toBeVisible()
  await priority.fill('7')
  await page.keyboard.press('Tab')
  await expect(choice).toBeFocused()
  await choice.selectOption('2')
  await page.keyboard.press('Tab')
  await expect(toggle).toBeFocused()
  await page.keyboard.press('Space')
  await expect(toggle).toBeChecked()
  await page.keyboard.press('Enter')
  await expect(toggle).not.toBeChecked()
  await page.getByText('Enabled', { exact: true }).click()
  await expect(toggle).toBeChecked()
  await slider.focus()
  await page.keyboard.press('ArrowRight')
  await expect(slider).toHaveValue('55')
  await page.keyboard.press('Tab')
  await expect(button).toBeFocused()
  await page.keyboard.press('Space')
  await expect(page.getByLabel('Listener deliveries')).toHaveText('{"input":1,"select":1,"toggle":3,"slider":1,"button":1}')
  await expect(page.getByLabel('Model values')).toHaveText('{"priority":7,"route":"2","enabled":true,"threshold":55}')
  await expect(page.getByLabel('Submissions', { exact: true })).toHaveText('0')
  await page.getByLabel('Disable controls').check()
  for (const control of [priority, choice, toggle, slider, button]) await expect(control).toBeDisabled()
  await expect(page.getByLabel('Listener deliveries')).toHaveText('{"input":1,"select":1,"toggle":3,"slider":1,"button":1}')
  expect(apiRequests).toEqual([])
  expect(errors).toEqual([])
})

test('native constraints and accessible error descriptions reach the input', async ({ page }) => {
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const priority = page.getByRole('spinbutton', { name: 'Priority', exact: true })
  await expect(priority).toHaveAccessibleDescription('Use a priority from 1 to 9. Review this priority')
  await expect(priority).toHaveAttribute('aria-invalid', 'true')
  await priority.fill('12')
  expect(await priority.evaluate(input => input.validity.rangeOverflow)).toBe(true)
  await priority.fill('')
  expect(await priority.evaluate(input => input.validity.valueMissing)).toBe(true)
  await priority.fill('3')
  expect(await priority.evaluate(input => input.checkValidity())).toBe(true)
  await page.getByRole('button', { name: 'Clear error' }).click()
  await expect(priority).not.toHaveAttribute('aria-invalid')
  await expect(priority).toHaveAccessibleDescription('Use a priority from 1 to 9.')
})

test('password commands retain keyboard focus, protect values and never submit on reveal', async ({ page }, testInfo) => {
  const errors = [], apiRequests = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(url => url.pathname.startsWith('/api/'), async route => {
    apiRequests.push(route.request().method())
    await route.abort()
  })
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const input = page.getByLabel('Provider key', { exact: true })
  const show = page.getByRole('button', { name: 'Show Provider key', exact: true })
  await expect(input).toHaveAttribute('type', 'password')
  await expect(input).toHaveAccessibleDescription('Use a dummy value only. Paste the complete key. Check the sample key')
  await expect(show).toHaveAttribute('aria-controls', await input.getAttribute('id'))
  await page.getByText('Provider key', { exact: true }).click()
  await expect(input).toBeFocused()
  await input.fill('  dummy<&é  ')
  await page.keyboard.press('Tab')
  await expect(show).toBeFocused()
  expect(await show.evaluate(button => globalThis.getComputedStyle(button).outlineStyle)).not.toBe('none')
  expect(await show.evaluate(button => parseFloat(globalThis.getComputedStyle(button).outlineWidth))).toBeGreaterThanOrEqual(2)
  await page.keyboard.press('Space')
  const hide = page.getByRole('button', { name: 'Hide Provider key', exact: true })
  await expect(hide).toBeFocused()
  await expect(input).toHaveAttribute('type', 'text')
  await expect(input).toHaveValue('  dummy<&é  ')
  await expect(input).toHaveAttribute('spellcheck', 'false')
  await page.keyboard.press('Enter')
  await expect(show).toBeFocused()
  await expect(input).toHaveAttribute('type', 'password')
  await expect(page.getByLabel('Credential deliveries')).toHaveText('1')
  await expect(page.getByLabel('Credential submissions')).toHaveText('0')
  await show.click()
  await page.getByLabel('Disable credential').check()
  await expect(input).toBeDisabled()
  await expect(show).toBeDisabled()
  await expect(input).toHaveAttribute('type', 'password')
  await page.getByLabel('Disable credential').uncheck()
  await expect(input).toHaveAttribute('type', 'password')
  await page.getByRole('button', { name: 'Show Read-only token' }).click()
  await expect(page.getByLabel('Read-only token', { exact: true })).toHaveAttribute('type', 'text')
  await expect(page.getByLabel('Read-only token', { exact: true })).not.toBeEditable()
  await expect(input).toHaveAttribute('type', 'password')
  expect(apiRequests).toEqual([])
  expect(errors).toEqual([])
  await page.setViewportSize({ width: 390, height: 844 })
  await input.focus()
  await page.keyboard.press('Tab')
  expect(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('password-input-mobile.png'), fullPage: true })
})

test('password native validation and submit concealment preserve help and model delivery', async ({ page }) => {
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const input = page.getByLabel('Provider key', { exact: true })
  await page.getByRole('button', { name: 'Save sample credential' }).click()
  expect(await input.evaluate(element => element.validity.valueMissing)).toBe(true)
  await expect(page.getByLabel('Credential submissions')).toHaveText('0')
  await input.fill('dummy-submission')
  await page.getByRole('button', { name: 'Clear credential error' }).click()
  await expect(input).not.toHaveAttribute('aria-invalid')
  await expect(input).toHaveAccessibleDescription('Use a dummy value only. Paste the complete key.')
  await page.getByRole('button', { name: 'Show Provider key' }).click()
  await page.getByRole('button', { name: 'Save sample credential' }).click()
  await expect(page.getByLabel('Submitted input type')).toHaveText('password')
  await expect(page.getByLabel('Credential submissions')).toHaveText('1')
  await expect(page.getByLabel('Credential deliveries')).toHaveText('1')
  await expect(input).toHaveValue('dummy-submission')
  await expect(input).toHaveAttribute('type', 'password')
  await expect(page.getByRole('button', { name: 'Show Provider key' })).toBeVisible()
})
