/* Classifarr - Copyright (C) 2024-2026 Classifarr Contributors - GPL-3.0 */
import { expect, test } from '@playwright/test'

test('real controls have names, native keyboard behavior and stable model types', async ({ page }) => {
  const errors = [], apiRequests = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(url => url.pathname.startsWith('/api/'), async route => {
    apiRequests.push(route.request().method())
    await route.abort()
  })
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const priority = page.getByRole('spinbutton', { name: 'Priority', exact: true })
  const choice = page.getByRole('combobox', { name: 'Route', exact: true })
  const toggle = page.getByRole('switch', { name: 'Enabled', exact: true })
  const slider = page.getByRole('slider', { name: 'Threshold', exact: true })
  await expect(priority).toBeVisible()
  await priority.fill('7')
  await page.keyboard.press('Tab')
  await expect(choice).toBeFocused()
  await choice.selectOption('2')
  await page.keyboard.press('Tab')
  await expect(toggle).toBeFocused()
  await page.keyboard.press('Space')
  await expect(toggle).toBeChecked()
  await page.keyboard.press('Enter')
  await expect(toggle).not.toBeChecked()
  await page.getByText('Enabled', { exact: true }).click()
  await expect(toggle).toBeChecked()
  await slider.focus()
  await page.keyboard.press('ArrowRight')
  await expect(slider).toHaveValue('55')
  await expect(page.getByLabel('Model values')).toHaveText('{"priority":7,"route":"2","enabled":true,"threshold":55}')
  await expect(page.getByLabel('Submissions')).toHaveText('0')
  await page.getByLabel('Disable controls').check()
  for (const control of [priority, choice, toggle, slider]) await expect(control).toBeDisabled()
  expect(apiRequests).toEqual([])
  expect(errors).toEqual([])
})

test('native constraints and accessible error descriptions reach the input', async ({ page }) => {
  await page.goto('/browser-tests/fixtures/shared-form-controls.html')
  const priority = page.getByRole('spinbutton', { name: 'Priority', exact: true })
  await expect(priority).toHaveAccessibleDescription('Use a priority from 1 to 9. Review this priority')
  await expect(priority).toHaveAttribute('aria-invalid', 'true')
  await priority.fill('12')
  expect(await priority.evaluate(input => input.validity.rangeOverflow)).toBe(true)
  await priority.fill('')
  expect(await priority.evaluate(input => input.validity.valueMissing)).toBe(true)
  await priority.fill('3')
  expect(await priority.evaluate(input => input.checkValidity())).toBe(true)
  await page.getByRole('button', { name: 'Clear error' }).click()
  await expect(priority).not.toHaveAttribute('aria-invalid')
  await expect(priority).toHaveAccessibleDescription('Use a priority from 1 to 9.')
})
