/* Classifarr - Copyright (C) 2024-2026 Classifarr Contributors - GPL-3.0 */
import { expect, test } from '@playwright/test'

test('manual tabs separate focus and selection, preserve tab order and never submit', async ({ page }) => {
  const errors = [], requests = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route(url => url.pathname.startsWith('/api/'), async route => {
    requests.push(route.request().method())
    await route.abort()
  })
  await page.goto('/browser-tests/fixtures/tabs.html')
  const form = page.locator('form')
  const list = page.getByRole('tablist', { name: 'Configuration sections' })
  const overview = list.getByRole('tab', { name: 'Overview 0', exact: true })
  const rules = list.getByRole('tab', { name: 'Rules', exact: true })
  const automation = list.getByRole('tab', { name: 'Automation details and health' })
  await page.getByRole('button', { name: 'Before tabs' }).focus()
  await page.keyboard.press('Tab')
  await expect(overview).toBeFocused()
  await overview.press('ArrowRight')
  await expect(rules).toBeFocused()
  await expect(overview).toHaveAttribute('aria-selected', 'true')
  await expect(rules).toHaveAttribute('aria-selected', 'false')
  await expect(form.getByRole('tabpanel', { name: 'Overview 0', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Rules action' })).toHaveCount(0)
  await rules.press('Tab')
  await expect(form.getByRole('tabpanel', { name: 'Overview 0', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(overview).toBeFocused()
  await overview.press('ArrowLeft')
  await expect(automation).toBeFocused()
  await automation.press('ArrowRight')
  await expect(overview).toBeFocused()
  await overview.press('End')
  await expect(automation).toBeFocused()
  await automation.press('Home')
  await expect(overview).toBeFocused()
  await overview.press('ArrowRight')
  await rules.press('Space')
  await expect(rules).toBeFocused()
  await expect(rules).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('button', { name: 'Overview action' })).toHaveCount(0)
  const panel = form.getByRole('tabpanel', { name: 'Rules', exact: true })
  await expect(panel).toHaveAttribute('id', await rules.getAttribute('aria-controls'))
  await expect(panel).toHaveAttribute('aria-labelledby', await rules.getAttribute('id'))
  await rules.press('Tab')
  await expect(panel).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Rules action' })).toBeFocused()
  await overview.focus()
  await overview.press('Enter')
  await automation.click()
  await automation.click()
  await expect(page.getByLabel('Selection deliveries')).toHaveText('3')
  await expect(page.getByLabel('Form submissions')).toHaveText('0')
  await expect(page.getByRole('tablist', { name: 'Secondary sections' }).getByRole('tab', { name: 'Overview 0' })).toHaveAttribute('aria-selected', 'true')
  const ids = await page.locator('[role="tab"], [role="tabpanel"]').evaluateAll(elements => elements.map(element => element.id))
  expect(new Set(ids).size).toBe(ids.length)
  expect(errors).toEqual([])
  expect(requests).toEqual([])
})

test('dynamic changes recover removed focus without stealing external focus', async ({ page }) => {
  await page.goto('/browser-tests/fixtures/tabs.html')
  const list = page.getByRole('tablist', { name: 'Configuration sections' })
  const rules = list.getByRole('tab', { name: 'Rules', exact: true })
  await rules.click()
  await expect(rules).toBeFocused()
  // Trigger a parent change without moving focus to the fixture's command.
  await page.getByRole('button', { name: 'Remove rules' }).evaluate(button => button.click())
  const overview = list.getByRole('tab', { name: 'Overview 0', exact: true })
  await expect(overview).toBeFocused()
  await expect(list.locator('[aria-selected="true"]')).toHaveCount(0)
  await expect(page.getByLabel('Selection deliveries')).toHaveText('1')
  await overview.press('Enter')
  await expect(page.getByLabel('Selected section')).toHaveText('overview')
  const external = page.getByRole('button', { name: 'Select automation externally' })
  await external.click()
  await expect(external).toBeFocused()
  await expect(list.getByRole('tab', { name: 'Automation details and health' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('Selection deliveries')).toHaveText('2')
})

test('focused tabs stay visible in a narrow scrolling list', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/browser-tests/fixtures/tabs.html')
  const list = page.getByRole('tablist', { name: 'Configuration sections' })
  await list.getByRole('tab', { name: 'Overview 0', exact: true }).focus()
  await page.keyboard.press('End')
  const target = list.getByRole('tab', { name: 'Automation details and health' })
  await expect(target).toBeFocused()
  const listBounds = await list.boundingBox(), targetBounds = await target.boundingBox()
  expect(targetBounds.x).toBeGreaterThanOrEqual(listBounds.x)
  expect(targetBounds.x + targetBounds.width).toBeLessThanOrEqual(listBounds.x + listBounds.width + 1)
  expect(await target.evaluate(element => globalThis.getComputedStyle(element).outlineStyle)).not.toBe('none')
  expect(await target.evaluate(element => parseFloat(globalThis.getComputedStyle(element).outlineWidth))).toBeGreaterThanOrEqual(2)
  expect(await page.evaluate(() => globalThis.document.documentElement.scrollWidth <= globalThis.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('tabs-mobile.png'), fullPage: true })
})
