-- Classifarr - AI-powered media classification for the *arr ecosystem
-- Copyright (C) 2024-2026 Classifarr Contributors
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program. If not, see <https://www.gnu.org/licenses/>.

-- Migration: 20260404_120000_add_classification_evidence.sql
--
-- PURPOSE
-- Introduces the canonical classification_evidence table as the target
-- persistence layer for the evidence unification project (Phase 2).
--
-- This table will eventually supersede learning_patterns and
-- discovered_patterns. During Phase 2, it is populated via backfill only.
-- Runtime reads remain on the legacy tables until Phase 4 cutover.
--
-- SAFETY — EXISTING INSTALLS
-- All DDL uses IF NOT EXISTS / CREATE INDEX IF NOT EXISTS / ON CONFLICT DO NOTHING
-- so this migration is safe to apply to any existing install.
--
-- SAFETY — FRESH INSTALLS
-- The table and all indexes are created at migration time. Fresh installs
-- will have the table ready before any backfill is run.
--
-- SCOPE SEMANTICS
--   item_exact    — exact human-confirmed item memory (may bypass AI)
--   genre         — learned genre affinity for a library
--   studio        — mined studio affinity
--   franchise     — mined franchise affinity
--   certification — mined certification affinity
--   profile_affinity — future: profile-derived affinity (reserved)
--
-- PROVENANCE SEMANTICS
--   human_confirmed  — written by a human correction flow
--   policy_confirmed — written by a policy-question resolution
--   discord_confirmed — written via Discord bot confirmation
--   retry_confirmed  — written after a retry cycle confirm
--   manual_correction — written by admin tool
--   mined            — generated by pattern mining or AI only
--
-- TRUST RULE
--   scope = item_exact + human_confirmed provenance → authoritative (may bypass AI)
--   All other scopes → scored evidence only, never authoritative by themselves.

CREATE TABLE IF NOT EXISTS classification_evidence (
    id                       BIGSERIAL PRIMARY KEY,
    scope                    VARCHAR(50)    NOT NULL,
    media_type               VARCHAR(20),
    library_id               INTEGER        REFERENCES libraries (id) ON DELETE CASCADE,
    tmdb_id                  INTEGER,
    evidence_key             VARCHAR(255),
    evidence_data            JSONB,
    provenance               VARCHAR(50)    NOT NULL,
    confidence               DECIMAL(5,2),
    usage_count              INTEGER        NOT NULL DEFAULT 0,
    success_rate             DECIMAL(5,2),
    status                   VARCHAR(20)    NOT NULL DEFAULT 'active',
    created_by               VARCHAR(100),
    source_classification_id BIGINT,
    source_system            VARCHAR(50),
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    last_seen_at             TIMESTAMPTZ,

    CONSTRAINT classification_evidence_scope_chk CHECK (
        scope IN (
            'item_exact', 'genre', 'studio', 'franchise',
            'certification', 'profile_affinity'
        )
    ),
    CONSTRAINT classification_evidence_provenance_chk CHECK (
        provenance IN (
            'human_confirmed', 'policy_confirmed', 'discord_confirmed',
            'retry_confirmed', 'manual_correction', 'mined', 'ai_only'
        )
    ),
    CONSTRAINT classification_evidence_status_chk CHECK (
        status IN ('active', 'candidate', 'decayed', 'archived')
    )
);

-- Unique partial index: exact item memory — one record per tmdb_id + media_type
-- NULL tmdb_id rows are excluded; they cannot be exact-match candidates.
CREATE UNIQUE INDEX IF NOT EXISTS idx_classification_evidence_item_exact
    ON classification_evidence (scope, tmdb_id, media_type)
    WHERE scope = 'item_exact'
      AND tmdb_id IS NOT NULL;

-- Unique partial index: related evidence — one record per scope + media_type + library + key
CREATE UNIQUE INDEX IF NOT EXISTS idx_classification_evidence_related
    ON classification_evidence (scope, media_type, library_id, evidence_key)
    WHERE scope IN ('genre', 'studio', 'franchise', 'certification');

-- Supporting lookups
CREATE INDEX IF NOT EXISTS idx_classification_evidence_library
    ON classification_evidence (library_id);

CREATE INDEX IF NOT EXISTS idx_classification_evidence_tmdb
    ON classification_evidence (tmdb_id)
    WHERE tmdb_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_classification_evidence_scope_status
    ON classification_evidence (scope, status);

-- updated_at trigger — conditional on the shared trigger function existing
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at_column'
    )
    AND NOT EXISTS (
        SELECT 1 FROM information_schema.triggers
        WHERE trigger_schema = 'public'
          AND event_object_table = 'classification_evidence'
          AND trigger_name = 'trg_classification_evidence_updated_at'
    ) THEN
        EXECUTE '
            CREATE TRIGGER trg_classification_evidence_updated_at
            BEFORE UPDATE ON classification_evidence
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
        ';
    END IF;
END $$;
