-- Classifarr - AI-powered media classification for the *arr ecosystem
-- Copyright (C) 2024-2026 Classifarr Contributors
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program. If not, see <https://www.gnu.org/licenses/>.

-- Durable, privacy-bounded receipts for saved strict-verification capability transitions.
-- This migration stores no provider, model, endpoint, credential, prompt, item,
-- policy, routing, or retry data.

ALTER TABLE ai_provider_config
    ADD COLUMN IF NOT EXISTS configuration_revision BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS candidate_bound_verification_capability_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id VARCHAR(156) NOT NULL,
    before_status_id VARCHAR(80) NOT NULL,
    after_status_id VARCHAR(80) NOT NULL,
    configuration_revision BIGINT NOT NULL,
    receipt_version VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT cbv_capability_receipts_actor_ck
        CHECK (actor_id ~ '^user:[A-Za-z0-9:_-]{1,150}$'),
    CONSTRAINT cbv_capability_receipts_status_ck
        CHECK (
            before_status_id IN (
                'verification_ready',
                'primary_path_ineligible',
                'budget_fallback_advisory',
                'primary_and_fallback_ineligible'
            )
            AND after_status_id IN (
                'verification_ready',
                'primary_path_ineligible',
                'budget_fallback_advisory',
                'primary_and_fallback_ineligible'
            )
            AND before_status_id <> after_status_id
        ),
    CONSTRAINT cbv_capability_receipts_revision_ck
        CHECK (configuration_revision > 0),
    CONSTRAINT cbv_capability_receipts_revision_uq
        UNIQUE (configuration_revision)
);

CREATE INDEX IF NOT EXISTS idx_cbv_capability_receipts_actor_id
    ON candidate_bound_verification_capability_receipts (actor_id, id DESC);
