import { SIGNAL_TYPES } from './signalCollector.mjs';

export const DEFAULT_WEIGHTS = {
    [SIGNAL_TYPES.SOURCE_LIBRARY]: 100,
    [SIGNAL_TYPES.MANUAL_CORRECTION]: 100,
    [SIGNAL_TYPES.EXISTING_MEDIA]: 100,
    [SIGNAL_TYPES.EXACT_MATCH]: 100,
    [SIGNAL_TYPES.SEMANTIC_SIMILARITY]: 75,
    [SIGNAL_TYPES.PROFILE_SCORE]: 60,
    [SIGNAL_TYPES.CUSTOM_RULE]: 35,
    [SIGNAL_TYPES.COLLECTION_MATCH]: 25,
    [SIGNAL_TYPES.LEARNED_PATTERN]: 20,
    [SIGNAL_TYPES.CONTENT_ANALYSIS]: 15,
    [SIGNAL_TYPES.KEYWORD_MATCH]: 10,
    [SIGNAL_TYPES.GENRE_MATCH]: 10,
};
