/*
 * Classifarr - AI-powered media classification for the *arr ecosystem
 * Copyright (C) 2024-2026 Classifarr Contributors
 */

import {
  POLICY_CANDIDATE_CONTRASTIVE_EVIDENCE_STATUS_IDS,
} from './policyCandidateContrastiveEvidence.mjs';
import {
  POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS,
  POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SEMANTIC_SIGNAL_IDS,
} from './policyCandidateEvidenceOfflineEvaluationContract.mjs';
import {
  POLICY_RUNTIME_CANDIDATE_SET_SELECTION_STATUS_IDS,
} from './policyRuntimeCandidateSetSelectionOutcome.mjs';

export const POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SIGNAL_IDS = Object.freeze({
  DETERMINISTIC_CANDIDATE_SCOPE: 'deterministic_candidate_scope',
  EXACT_CONTRASTIVE_STATUS: 'exact_contrastive_status',
  SEMANTIC_RETRIEVAL_PROPOSAL: 'semantic_retrieval_proposal',
});

const DECISION_BY_SELECTION_STATUS = Object.freeze({
  [POLICY_RUNTIME_CANDIDATE_SET_SELECTION_STATUS_IDS.CONFIRMED_CANDIDATE]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ADMIT,
  [POLICY_RUNTIME_CANDIDATE_SET_SELECTION_STATUS_IDS.CHANGED_TO_CANDIDATE]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ADMIT,
  [POLICY_RUNTIME_CANDIDATE_SET_SELECTION_STATUS_IDS.CHANGED_OUTSIDE_CANDIDATES]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.REVIEW,
  [POLICY_RUNTIME_CANDIDATE_SET_SELECTION_STATUS_IDS.ROUTED_NOT_APPLICABLE]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ABSTAIN,
});

const DECISION_BY_CONTRASTIVE_STATUS = Object.freeze({
  [POLICY_CANDIDATE_CONTRASTIVE_EVIDENCE_STATUS_IDS.LEADING_IDENTITY_MATCH]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ADMIT,
  [POLICY_CANDIDATE_CONTRASTIVE_EVIDENCE_STATUS_IDS.ALTERNATIVE_IDENTITY_MATCH]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.REVIEW,
  [POLICY_CANDIDATE_CONTRASTIVE_EVIDENCE_STATUS_IDS.SHARED_IDENTITY_MATCH]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ABSTAIN,
  [POLICY_CANDIDATE_CONTRASTIVE_EVIDENCE_STATUS_IDS.NO_CANDIDATE_IDENTITY_MATCH]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.REVIEW,
  [POLICY_CANDIDATE_CONTRASTIVE_EVIDENCE_STATUS_IDS.IDENTITY_UNVERIFIED]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ABSTAIN,
  [POLICY_CANDIDATE_CONTRASTIVE_EVIDENCE_STATUS_IDS.RETRIEVAL_UNAVAILABLE]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ABSTAIN,
});

const DECISION_BY_SEMANTIC_SIGNAL = Object.freeze({
  [POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SEMANTIC_SIGNAL_IDS.SUPPORTS_LEADING_CANDIDATE]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ADMIT,
  [POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SEMANTIC_SIGNAL_IDS.SUPPORTS_ALTERNATIVE_CANDIDATE]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.REVIEW,
  [POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SEMANTIC_SIGNAL_IDS.ABSTAIN]:
    POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_DECISION_IDS.ABSTAIN,
});

function mappedDecision(mapping, value) {
  return typeof value === 'string' && Object.hasOwn(mapping, value)
    ? mapping[value]
    : null;
}

export function mapPolicyCandidateSelectionStatusToOfflineDecision(statusId) {
  return mappedDecision(DECISION_BY_SELECTION_STATUS, statusId);
}

export function mapPolicyCandidateContrastiveStatusToOfflineDecision(statusId) {
  return mappedDecision(DECISION_BY_CONTRASTIVE_STATUS, statusId);
}

export function mapPolicyCandidateSemanticSignalToOfflineDecision(signalId) {
  return mappedDecision(DECISION_BY_SEMANTIC_SIGNAL, signalId);
}

/**
 * Maps the three fixed evidence dimensions into offline-only decisions. The
 * result is intentionally a test artifact and has no path to routing, policy,
 * model invocation, learning, or an operator recommendation.
 */
export function buildPolicyCandidateEvidenceOfflineSignalDecisions(observations = {}) {
  return Object.freeze({
    [POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SIGNAL_IDS.DETERMINISTIC_CANDIDATE_SCOPE]:
      mapPolicyCandidateSelectionStatusToOfflineDecision(observations.candidateSetSelectionStatusId),
    [POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SIGNAL_IDS.EXACT_CONTRASTIVE_STATUS]:
      mapPolicyCandidateContrastiveStatusToOfflineDecision(observations.contrastiveStatusId),
    [POLICY_CANDIDATE_EVIDENCE_OFFLINE_EVALUATION_SIGNAL_IDS.SEMANTIC_RETRIEVAL_PROPOSAL]:
      mapPolicyCandidateSemanticSignalToOfflineDecision(observations.semanticRetrievalSignalId),
  });
}
