/*
 * Classifarr - AI-powered media classification for the *arr ecosystem
 * Copyright (C) 2024-2026 Classifarr Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

import {
  POLICY_PROFILE_REFRESH_OUTBOX_WORKER_FAILURE_IDS,
} from './policyProfileRefreshOutboxWorkerVocabulary.mjs';

const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_VERSION =
  'policy.native_profile_refresh_circuit.v1';

const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_STATE_IDS = Object.freeze({
  CLOSED: 'closed',
  OPEN: 'open',
  HALF_OPEN: 'half_open',
});

const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_ACTION_IDS = Object.freeze({
  BLOCK: 'block',
  ENQUEUE_PRIMARY: 'enqueue_primary',
  ENQUEUE_PROBE: 'enqueue_probe',
});

const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_FAILURE_THRESHOLD = 3;
const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_PROBE_DELAY_MS = 2 * 60 * 60 * 1000;
const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_COALESCED_PROBE_DELAY_MS = 5 * 60 * 1000;
const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_RETENTION_DAYS = 30;

const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_RECOVERABLE_FAILURE_CODES = Object.freeze([
  POLICY_PROFILE_REFRESH_OUTBOX_WORKER_FAILURE_IDS.EXECUTION_FAILED,
  POLICY_PROFILE_REFRESH_OUTBOX_WORKER_FAILURE_IDS.LEASE_EXPIRED,
  POLICY_PROFILE_REFRESH_OUTBOX_WORKER_FAILURE_IDS.TRANSIENT_DEPENDENCY_FAILED,
  POLICY_PROFILE_REFRESH_OUTBOX_WORKER_FAILURE_IDS.UNKNOWN_FAILED,
]);

const POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_CONFIGURATION_FAILURE_CODE =
  POLICY_PROFILE_REFRESH_OUTBOX_WORKER_FAILURE_IDS.CONFIGURATION_INVALID;

function isPolicyNativeProfileRefreshCircuitFailureCode(value) {
  return value === POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_CONFIGURATION_FAILURE_CODE ||
    POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_RECOVERABLE_FAILURE_CODES.includes(value);
}

export {
  isPolicyNativeProfileRefreshCircuitFailureCode,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_ACTION_IDS,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_COALESCED_PROBE_DELAY_MS,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_CONFIGURATION_FAILURE_CODE,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_FAILURE_THRESHOLD,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_PROBE_DELAY_MS,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_RECOVERABLE_FAILURE_CODES,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_RETENTION_DAYS,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_STATE_IDS,
  POLICY_NATIVE_PROFILE_REFRESH_CIRCUIT_VERSION,
};
